### PR TITLE
Updated Import-VMHOstNetworkingfromCSV and Export-VMHostNetworkingToCSV to include support for VDS Switches and Port Groups

### PR DESCRIPTION
**Pull request by nshores**
Before updates errors would occur when exporting networking data that includes hosts connected to VDS switches. -- Example is attached. I have updated the import and export functions to handle VDS switches and portgroups without errors. 

[vds_errors.txt](https://github.com/Dapacruz/VMware.VimAutomation.Custom/files/1718867/vds_errors.txt)

### CODE REVIEW

**Comment by dapacruz** [comment]
Functions/Public/Import-VMHostNetworkingFromCsv.ps1

Why is line 106 commented out?

**Comment by nshores** [comment]
Leftover from troubleshooting, comment can be removed

**Comment by dapacruz** [comment]
I am still getting errors when exporting VDS configurations. Please fix and resubmit.

> $ Export-VMHostNetworkingToCsv -VMHost rmiesxi01.rci.local -IncludeIscsiAdapter
Get-NicTeamingPolicy : Cannot bind parameter 'VirtualPortGroup'. Cannot convert the "VOIP" value of type
"VMware.VimAutomation.ViCore.Impl.V1.Host.Networking.DistributedPortGroupImpl" to type "VMware.VimAutomation.ViCore.Types.V1.Host.Networking.VirtualPortGroup".
At C:\Users\admin\Documents\WindowsPowerShell\Modules\VMware.VimAutomation.Custom\VMware.VimAutomation.Custom.psm1:463 char:78
+ ...       $nic_teaming_policy = Get-NicTeamingPolicy -VirtualPortGroup $s
+                                                                        ~~
    + CategoryInfo          : InvalidArgument: (:) [Get-NicTeamingPolicy], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,VMware.VimAutomation.ViCore.Cmdlets.Commands.Host.GetNicTeamingPolicy

**Comment by nshores** [comment]
Here's the same exact code in a PS1 file by itself. Runs fine on my machine. Attached is the CSV files generated. I'm not sure where the difference is here..

https://gist.github.com/nshores/673535b8bab1ca7669be309da28ea3d5


[temp.zip](https://github.com/Dapacruz/VMware.VimAutomation.Custom/files/1722845/temp.zip)


image

**Comment by dapacruz** [comment]
OK, so I got this working. Turns out this was my fault. I needed to update the symlink to my Posh profile due to some previous changes to the module. That being said, this needs some work.

1. "Nic" names are being exported incorrectly: "Uplink,1,Uplink,2,Uplink,3,Uplink,4" in the virtual port groups spreadsheet. This is due to the difference in naming convention from standard switches (vmnic0, etc.). It should be: "'Uplink 1', 'Uplink 2', 'Uplink 3', 'Uplink 4'".
2. The "Nic" column of the virtual switches spreadsheet is blank.
3. Get-VDSwitch should be used instead of Get-VirtualSwitch.
4. One final note, please maintain the order that the properties are added to objects. This affects the order they appear in the spreadsheet.

**Pull request closed without merging**
