### PR TITLE
Updated import and export networking functions to include support for VDS. 

### PR DESCRIPTION
**Pull request by nshores**

### CODE REVIEW

**Comment by dapacruz** [comment]
This is great. I will look it over more thoroughly very soon. Thank you!

**Comment by dapacruz** [comment]
Did you fully test these changes with standard and VDS switches?

**Comment by dapacruz** [comment]
I am seeing the following errors and the export is incomplete for VDS.

WARNING: The output of the command produced distributed virtual portgroup objects. This behavior is obsolete and may change in the future. To retrieve distributed portgroups, use
Get-VDPortgroup cmdlet in the VDS component. To retrieve standard portgroups, use -Standard.

Get-NicTeamingPolicy : Cannot bind parameter 'VirtualPortGroup'. Cannot convert the "VOIP" value of type
"VMware.VimAutomation.ViCore.Impl.V1.Host.Networking.DistributedPortGroupImpl" to type "VMware.VimAutomation.ViCore.Types.V1.Host.Networking.VirtualPortGroup".
At C:\Users\admin\Documents\WindowsPowerShell\Modules\VMware.VimAutomation.Custom\VMware.VimAutomation.Custom.psm1:463 char:78
+ ...       $nic_teaming_policy = Get-NicTeamingPolicy -VirtualPortGroup $s
+                                                                        ~~
    + CategoryInfo          : InvalidArgument: (:) [Get-NicTeamingPolicy], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,VMware.VimAutomation.ViCore.Cmdlets.Commands.Host.GetNicTeamingPolicy

**Comment by nshores** [comment]
I was not seeing any errors when testing. I will run it against my lab and see where the issue is. It appears it may have an issue on standard vswitches now.

On Feb 12, 2018 7:04 PM, David Cruz <notifications@github.com> wrote:

I am seeing the following errors and the export is incomplete for VDS.

WARNING: The output of the command produced distributed virtual portgroup objects. This behavior is obsolete and may change in the future. To retrieve distributed portgroups, use
Get-VDPortgroup cmdlet in the VDS component. To retrieve standard portgroups, use -Standard.

Get-NicTeamingPolicy : Cannot bind parameter 'VirtualPortGroup'. Cannot convert the "VOIP" value of type
"VMware.VimAutomation.ViCore.Impl.V1.Host.Networking.DistributedPortGroupImpl" to type "VMware.VimAutomation.ViCore.Types.V1.Host.Networking.VirtualPortGroup".
At C:\Users\admin\Documents\WindowsPowerShell\Modules\VMware.VimAutomation.Custom\VMware.VimAutomation.Custom.psm1:463 char:78

  *   ... $nic_teaming_policy = Get-NicTeamingPolicy -VirtualPortGroup $s
  *

                                                                   ~~


     *   CategoryInfo : InvalidArgument: (:) [Get-NicTeamingPolicy], ParameterBindingException
     *   FullyQualifiedErrorId : CannotConvertArgumentNoMessage,VMware.VimAutomation.ViCore.Cmdlets.Commands.Host.GetNicTeamingPolicy

**Comment by dapacruz** [comment]
I ran a standard switch export and it seemed to work fine.

**Comment by nshores** [comment]
I am able to run it without errors --


[8:14:41 PM] Z:/Documents/Roebbelen/test> \\vmware-host\Shared Folders\Documents\WindowsPowerShell\Modules\Dev\VMware.VimAutomation.Custom\export-vmhostnetworkingtocsv-dev.ps1
WARNING: The output of the command produced distributed virtual switch objects. This behavior is obsolete
 and may change in the future. To retrieve distributed switches, use Get-VDSwitch cmdlet in the VDS compo
nent. To retrieve standard switches, use -Standard.
WARNING: The output of the command produced distributed virtual portgroup objects. This behavior is obsol
ete and may change in the future. To retrieve distributed portgroups, use Get-VDPortgroup cmdlet in the V
DS component. To retrieve standard portgroups, use -Standard.

[8:15:03 PM] Z:/Documents/Roebbelen/test>

________________________________

**Comment by dapacruz** [comment]
As we discussed, please re-implement and test, and then resubmit your pull
request after I merge the changes to separate the cmdlets into their own
files. Thanks.

**Pull request closed without merging**
